version: 2.1

jobs:
  build-and-test:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -f Dockerfile.travis -t build .
          name: Build
      - run:
          command: docker run --name pytest build pytest --junitxml=./cov.xml
          name: Test
      - run:
          command: docker cp pytest:/app/cov.xml ./
          name: Copy artifact
    - store_artifacts:
        path: ./cov.xml

workflows:
  main:
    jobs:
      - build-and-test
